parameters:
  - name: workloadType
    type: string
  - name: subscriptionId
    type: string
  - name: rgName
    type: string
  - name: storageAccount1
    type: string
    default: ''
  - name: storageAccount2
    type: string
    default: ''
  - name: runSetupStages
    type: boolean
    default: false
  - name: dependsOn
    type: object
    default: []

stages:
  - stage: DataPathTests_${{ replace(parameters.workloadType, '-', '_') }}
    displayName: "Stage: Swiftv2 Data Path Tests - ${{ parameters.workloadType }}"
    ${{ if ne(length(parameters.dependsOn), 0) }}:
      dependsOn: ${{ parameters.dependsOn }}
    ${{ else }}:
      dependsOn: AKSClusterAndNetworking
    condition: or(eq(${{ parameters.runSetupStages }}, false), succeeded())
    variables:
      storageAccount1: ${{ parameters.storageAccount1 }}
      storageAccount2: ${{ parameters.storageAccount2 }}
    jobs:
      - job: SetupKubeconfig
        displayName: "Setup Kubeconfig Files"
        steps:
          - task: AzureCLI@2
            displayName: "Generate and verify kubeconfig files"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                mkdir -p $(Pipeline.Workspace)/kubeconfigs
                
                echo "==> Setting up kubeconfig for cluster aks-1"
                az aks get-credentials \
                  --resource-group ${{ parameters.rgName }} \
                  --name aks-1 \
                  --file $(Pipeline.Workspace)/kubeconfigs/aks-1.kubeconfig \
                  --overwrite-existing \
                  --admin
                
                echo "==> Setting up kubeconfig for cluster aks-2"
                az aks get-credentials \
                  --resource-group ${{ parameters.rgName }} \
                  --name aks-2 \
                  --file $(Pipeline.Workspace)/kubeconfigs/aks-2.kubeconfig \
                  --overwrite-existing \
                  --admin
                
                echo "==> Verifying cluster aks-1 connectivity"
                kubectl --kubeconfig $(Pipeline.Workspace)/kubeconfigs/aks-1.kubeconfig get nodes
                
                echo "==> Verifying cluster aks-2 connectivity"
                kubectl --kubeconfig $(Pipeline.Workspace)/kubeconfigs/aks-2.kubeconfig get nodes

          - task: PublishPipelineArtifact@1
            displayName: "Publish kubeconfig files"
            inputs:
              targetPath: $(Pipeline.Workspace)/kubeconfigs
              artifactName: kubeconfigs-${{ parameters.workloadType }}
              publishLocation: pipeline

      - job: BuildMetricsBinary
        displayName: "Build Metrics Binary"
        steps:
          - checkout: Networking-Aquarius
            displayName: "Checkout Networking-Aquarius repository"

          - task: Bash@3
            displayName: "Build persistent-cluster-metrics binary"
            inputs:
              targetType: 'inline'
              script: |
                make -C src/dnc persistent-cluster-metrics-binary
                chmod +x src/dnc/output/linux_amd64/metrics/persistent-cluster-metrics

          - task: PublishPipelineArtifact@1
            displayName: "Publish metrics binary and config"
            inputs:
              targetPath: '$(System.DefaultWorkingDirectory)/src/dnc'
              artifact: 'persistent-cluster-metrics-${{ parameters.workloadType }}'
              publishLocation: 'pipeline'

      - job: CreatePods
        displayName: "Create Swiftv2 Pods"
        dependsOn:
          - SetupKubeconfig
          - BuildMetricsBinary
        steps:
          - template: metrics-setup-steps.yaml
            parameters:
              workloadType: ${{ parameters.workloadType }}

          - task: AzureCLI@2
            name: RunCreatePods
            displayName: "Create pods"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "==> Creating pods (8 scenarios) for workload type: ${{ parameters.workloadType }}"
                export RG="${{ parameters.rgName }}"
                export BUILD_ID="${{ parameters.rgName }}"
                export WORKLOAD_TYPE="${{ parameters.workloadType }}"
                
                metrics_dir="$(System.DefaultWorkingDirectory)/Networking-Aquarius/src/dnc"
                ado_run_id="$(Build.BuildId)"
                
                cd $(System.DefaultWorkingDirectory)/azure-container-networking/test/integration/swiftv2/longRunningCluster
                
                if go test -v -timeout=1h -tags=create_test; then
                  echo "CreatePods test PASSED"
                  cd $metrics_dir
                  output/linux_amd64/metrics/persistent-cluster-metrics --metric-name "PersistentClusterTestsSucceeded" --ado-run-id $ado_run_id --resource-group "$RG" --cluster-type "${{ parameters.workloadType }}" --test-scenario "Pod creation"
                else
                  echo "CreatePods test FAILED"
                  cd $metrics_dir
                  output/linux_amd64/metrics/persistent-cluster-metrics --metric-name "PersistentClusterTestsFailed" --ado-run-id $ado_run_id --resource-group "$RG" --cluster-type "${{ parameters.workloadType }}" --test-scenario "Pod creation"
                  exit 1
                fi
              workingDirectory: $(System.DefaultWorkingDirectory)
            env:
              KUBECONFIG: $(Pipeline.Workspace)/kubeconfigs/aks-1.kubeconfig:$(Pipeline.Workspace)/kubeconfigs/aks-2.kubeconfig
              KUBECONFIG_DIR: $(Pipeline.Workspace)/kubeconfigs

      - job: ConnectivityTests
        displayName: "Test Pod-to-Pod Connectivity"
        dependsOn: CreatePods
        steps:
          - template: metrics-setup-steps.yaml
            parameters:
              workloadType: ${{ parameters.workloadType }}

          - task: AzureCLI@2
            displayName: "Run Connectivity Tests"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "==> Running connectivity tests for workload type: ${{ parameters.workloadType }}"
                export RG="${{ parameters.rgName }}"
                export BUILD_ID="${{ parameters.rgName }}"
                export WORKLOAD_TYPE="${{ parameters.workloadType }}"
                
                metrics_dir="$(System.DefaultWorkingDirectory)/Networking-Aquarius/src/dnc"
                ado_run_id="$(Build.BuildId)"
                
                cd $(System.DefaultWorkingDirectory)/azure-container-networking/test/integration/swiftv2/longRunningCluster
                
                if go test -v -timeout=30m -tags=connectivity_test; then
                  echo "ConnectivityTests test PASSED"
                  cd $metrics_dir
                  output/linux_amd64/metrics/persistent-cluster-metrics --metric-name "PersistentClusterTestsSucceeded" --ado-run-id $ado_run_id --resource-group "$RG" --cluster-type "${{ parameters.workloadType }}" --test-scenario "Connectivity tests"
                else
                  echo "ConnectivityTests test FAILED"
                  cd $metrics_dir
                  output/linux_amd64/metrics/persistent-cluster-metrics --metric-name "PersistentClusterTestsFailed" --ado-run-id $ado_run_id --resource-group "$RG" --cluster-type "${{ parameters.workloadType }}" --test-scenario "Connectivity tests"
                  exit 1
                fi
              workingDirectory: $(System.DefaultWorkingDirectory)
            env:
              KUBECONFIG: $(Pipeline.Workspace)/kubeconfigs/aks-1.kubeconfig:$(Pipeline.Workspace)/kubeconfigs/aks-2.kubeconfig
              KUBECONFIG_DIR: $(Pipeline.Workspace)/kubeconfigs

      - job: PrivateEndpointTests
        displayName: "Test Private Endpoint Access"
        dependsOn: ConnectivityTests
        steps:
          - template: metrics-setup-steps.yaml
            parameters:
              workloadType: ${{ parameters.workloadType }}

          - task: AzureCLI@2
            name: DiscoverStorageAccounts
            displayName: "Discover storage accounts"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                STORAGE_ACCOUNT_1="${{ parameters.storageAccount1 }}"
                STORAGE_ACCOUNT_2="${{ parameters.storageAccount2 }}"
                
                if [ -z "$STORAGE_ACCOUNT_1" ] || [ -z "$STORAGE_ACCOUNT_2" ]; then
                  echo "Storage account variables not set, discovering from resource group..."
                  STORAGE_ACCOUNT_1=$(az storage account list -g ${{ parameters.rgName }} --query "[?starts_with(name, 'sa1')].name" -o tsv)
                  STORAGE_ACCOUNT_2=$(az storage account list -g ${{ parameters.rgName }} --query "[?starts_with(name, 'sa2')].name" -o tsv)
                  echo "Discovered: STORAGE_ACCOUNT_1=$STORAGE_ACCOUNT_1, STORAGE_ACCOUNT_2=$STORAGE_ACCOUNT_2"
                fi
                
                echo "##vso[task.setvariable variable=storageAccount1;isOutput=true]$STORAGE_ACCOUNT_1"
                echo "##vso[task.setvariable variable=storageAccount2;isOutput=true]$STORAGE_ACCOUNT_2"

          - task: AzureCLI@2
            displayName: "Assign RBAC for SAS token generation"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: scriptPath
              scriptPath: "azure-container-networking/.pipelines/swiftv2-long-running/scripts/manage_storage_rbac.sh"
              arguments: >
                assign
                ${{ parameters.subscriptionId }}
                ${{ parameters.rgName }}
                "$(DiscoverStorageAccounts.storageAccount1)"

          - task: AzureCLI@2
            displayName: "Run Private Endpoint Tests"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "==> Running Private Endpoint connectivity tests for workload type: ${{ parameters.workloadType }}"
                export RG="${{ parameters.rgName }}"
                export BUILD_ID="${{ parameters.rgName }}"
                export WORKLOAD_TYPE="${{ parameters.workloadType }}"
                export STORAGE_ACCOUNT_1="$(DiscoverStorageAccounts.storageAccount1)"
                export STORAGE_ACCOUNT_2="$(DiscoverStorageAccounts.storageAccount2)"
                
                metrics_dir="$(System.DefaultWorkingDirectory)/Networking-Aquarius/src/dnc"
                ado_run_id="$(Build.BuildId)"
                
                cd $(System.DefaultWorkingDirectory)/azure-container-networking/test/integration/swiftv2/longRunningCluster
                
                if go test -v -timeout=30m -tags=private_endpoint_test; then
                  echo "PrivateEndpointTests test PASSED"
                  cd $metrics_dir
                  output/linux_amd64/metrics/persistent-cluster-metrics --metric-name "PersistentClusterTestsSucceeded" --ado-run-id $ado_run_id --resource-group "$RG" --cluster-type "${{ parameters.workloadType }}" --test-scenario "Private endpoint tests"
                else
                  echo "PrivateEndpointTests test FAILED"
                  cd $metrics_dir
                  output/linux_amd64/metrics/persistent-cluster-metrics --metric-name "PersistentClusterTestsFailed" --ado-run-id $ado_run_id --resource-group "$RG" --cluster-type "${{ parameters.workloadType }}" --test-scenario "Private endpoint tests"
                  exit 1
                fi
              workingDirectory: $(System.DefaultWorkingDirectory)
            env:
              KUBECONFIG: $(Pipeline.Workspace)/kubeconfigs/aks-1.kubeconfig:$(Pipeline.Workspace)/kubeconfigs/aks-2.kubeconfig
              KUBECONFIG_DIR: $(Pipeline.Workspace)/kubeconfigs

          - task: AzureCLI@2
            displayName: "Remove RBAC after tests"
            condition: always()
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: scriptPath
              scriptPath: "azure-container-networking/.pipelines/swiftv2-long-running/scripts/manage_storage_rbac.sh"
              arguments: >
                delete
                ${{ parameters.subscriptionId }}
                ${{ parameters.rgName }}
                "$(DiscoverStorageAccounts.storageAccount1) $(DiscoverStorageAccounts.storageAccount2)"
      
      - job: ScaleTest
        displayName: "Scale Tests - create and delete pods at scale"
        dependsOn: PrivateEndpointTests
        steps:
          - template: metrics-setup-steps.yaml
            parameters:
              workloadType: ${{ parameters.workloadType }}

          - task: AzureCLI@2
            displayName: "Run Scale Test (Create and Delete)"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "==> Running scale test for workload type: ${{ parameters.workloadType }}"
                echo "  - 10 pods in aks-1 (cx_vnet_v1/s1)"
                echo "  - 10 pods in aks-2 (cx_vnet_v3/s1)"
                export RG="${{ parameters.rgName }}"
                export BUILD_ID="${{ parameters.rgName }}"
                export WORKLOAD_TYPE="${{ parameters.workloadType }}"
                
                metrics_dir="$(System.DefaultWorkingDirectory)/Networking-Aquarius/src/dnc"
                ado_run_id="$(Build.BuildId)"
                
                cd $(System.DefaultWorkingDirectory)/azure-container-networking/test/integration/swiftv2/longRunningCluster
                
                if go test -v -timeout 1h -tags=scale_test; then
                  echo "ScaleTest test PASSED"
                  cd $metrics_dir
                  output/linux_amd64/metrics/persistent-cluster-metrics --metric-name "PersistentClusterTestsSucceeded" --ado-run-id $ado_run_id --resource-group "$RG" --cluster-type "${{ parameters.workloadType }}" --test-scenario "Scale tests"
                else
                  echo "ScaleTest test FAILED"
                  cd $metrics_dir
                  output/linux_amd64/metrics/persistent-cluster-metrics --metric-name "PersistentClusterTestsFailed" --ado-run-id $ado_run_id --resource-group "$RG" --cluster-type "${{ parameters.workloadType }}" --test-scenario "Scale tests"
                  exit 1
                fi
              workingDirectory: $(System.DefaultWorkingDirectory)
            env:
              KUBECONFIG: $(Pipeline.Workspace)/kubeconfigs/aks-1.kubeconfig:$(Pipeline.Workspace)/kubeconfigs/aks-2.kubeconfig
              KUBECONFIG_DIR: $(Pipeline.Workspace)/kubeconfigs

      - job: DeleteTestResources
        displayName: "Delete PodNetwork, PNI, and Pods"
        dependsOn: 
          - CreatePods
          - ConnectivityTests
          - PrivateEndpointTests
          - ScaleTest
        condition: always()
        steps:
          - template: metrics-setup-steps.yaml
            parameters:
              workloadType: ${{ parameters.workloadType }}

          - task: AzureCLI@2
            displayName: "Delete Test Resources"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "==> Deleting test resources (8 scenarios) for workload type: ${{ parameters.workloadType }}"
                export RG="${{ parameters.rgName }}"
                export BUILD_ID="${{ parameters.rgName }}"
                export WORKLOAD_TYPE="${{ parameters.workloadType }}"
                
                metrics_dir="$(System.DefaultWorkingDirectory)/Networking-Aquarius/src/dnc"
                ado_run_id="$(Build.BuildId)"
                
                cd $(System.DefaultWorkingDirectory)/azure-container-networking/test/integration/swiftv2/longRunningCluster
                
                if go test -v -timeout=1h -tags=delete_test; then
                  echo "DeleteTestResources test PASSED"
                  cd $metrics_dir
                  output/linux_amd64/metrics/persistent-cluster-metrics --metric-name "PersistentClusterTestsSucceeded" --ado-run-id $ado_run_id --resource-group "$RG" --cluster-type "${{ parameters.workloadType }}" --test-scenario "Delete test resources"
                else
                  echo "DeleteTestResources test FAILED"
                  cd $metrics_dir
                  output/linux_amd64/metrics/persistent-cluster-metrics --metric-name "PersistentClusterTestsFailed" --ado-run-id $ado_run_id --resource-group "$RG" --cluster-type "${{ parameters.workloadType }}" --test-scenario "Delete test resources"
                  exit 1
                fi
              workingDirectory: $(System.DefaultWorkingDirectory)
            env:
              KUBECONFIG: $(Pipeline.Workspace)/kubeconfigs/aks-1.kubeconfig:$(Pipeline.Workspace)/kubeconfigs/aks-2.kubeconfig
              KUBECONFIG_DIR: $(Pipeline.Workspace)/kubeconfigs
