parameters:
  - name: subscriptionId
    type: string
  - name: location
    type: string
  - name: resourceGroupName
    type: string
  - name: runSetupStages
    type: boolean
    default: false
  - name: workloadType
    type: object
    default: [ "swiftv2-linux", "swiftv2-linux-byon" ]
    displayName: "Swiftv2 scenarios to run"


resources:
  repositories:
    - repository: Networking-Aquarius
      type: git
      name: One/Networking-Aquarius
      ref: refs/heads/master

variables:
  - name: rgName
    ${{ if eq(parameters.runSetupStages, true) }}:
      value: ${{ parameters.resourceGroupName }}
    ${{ else }}:
      value: sv2-long-run-${{ parameters.location }}
  - name: vmSkuDefault
    value: "Standard_D4s_v3"
  - name: vmSkuHighNIC
    value: "Standard_D16s_v3"

stages:
  - stage: AKSClusterAndNetworking
    displayName: "Stage: AKS Cluster and Networking Setup"
    condition: eq(${{ parameters.runSetupStages }}, true)
    jobs:
      - job: CreateResourceGroup
        displayName: "Create Resource Group"
        steps:
          - task: AzureCLI@2
            displayName: "Create resource group"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                echo "==> Creating resource group $(rgName) in ${{ parameters.location }}"
                az group create \
                  --name "$(rgName)" \
                  --location "${{ parameters.location }}" \
                  --subscription "${{ parameters.subscriptionId }}"
                echo "Resource group created successfully."

      - job: CreateCluster
        displayName: "Create AKS Clusters"
        dependsOn: CreateResourceGroup
        steps:
          - task: AzureCLI@2
            displayName: "Create AKS clusters"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: scriptPath
              scriptPath: ".pipelines/swiftv2-long-running/scripts/create_aks.sh"
              arguments: >
                ${{ parameters.subscriptionId }}
                ${{ parameters.location }}
                $(rgName)
                $(vmSkuDefault)
                $(vmSkuHighNIC)
                $(DELEGATOR_CONTAINER_APP_NAME)
                $(DELEGATOR_RESOURCE_GROUP)
                $(DELEGATOR_SUBSCRIPTION)
      
      - job: NetworkingAndStorage
        displayName: "Networking and Storage Setup"
        dependsOn: CreateCluster
        steps:
          - task: AzureCLI@2
            displayName: "Create customer vnets"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: scriptPath
              scriptPath: ".pipelines/swiftv2-long-running/scripts/create_vnets.sh"
              arguments: >
                ${{ parameters.subscriptionId }}
                ${{ parameters.location }}
                $(rgName)
                $(Build.BuildId)
                $(DELEGATOR_CONTAINER_APP_NAME)
                $(DELEGATOR_RESOURCE_GROUP)
                $(DELEGATOR_SUBSCRIPTION)

          - task: AzureCLI@2
            displayName: "Create customer vnet peerings"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: scriptPath
              scriptPath: ".pipelines/swiftv2-long-running/scripts/create_peerings.sh"
              arguments: >
                $(rgName)

          - task: AzureCLI@2
            name: CreateStorageAccounts
            displayName: "Create storage accounts"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: scriptPath
              scriptPath: ".pipelines/swiftv2-long-running/scripts/create_storage.sh"
              arguments: >
                ${{ parameters.subscriptionId }}
                ${{ parameters.location }}
                $(rgName)

          - task: AzureCLI@2
            displayName: "Create Private Endpoint for Storage Account"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: scriptPath
              scriptPath: ".pipelines/swiftv2-long-running/scripts/create_pe.sh"
              arguments: >
                ${{ parameters.subscriptionId }}
                ${{ parameters.location }}
                $(rgName)
                $(CreateStorageAccounts.StorageAccount1)
          
          - task: AzureCLI@2
            displayName: "Create network security groups to restrict access between subnets"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: scriptPath
              scriptPath: ".pipelines/swiftv2-long-running/scripts/create_nsg.sh"
              arguments: >
                ${{ parameters.subscriptionId }}
                $(rgName)
                ${{ parameters.location }}
      - job: DeployLinuxBYON
        displayName: "Join Linux BYON VMSS to AKS Cluster"
        dependsOn:
          - CreateCluster
          - NetworkingAndStorage
        pool:
          vmImage: ubuntu-latest
        steps:
          - checkout: self
            displayName: "Checkout main repository"
          - checkout: Networking-Aquarius
            displayName: "Checkout Networking-Aquarius repository"
          - task: AzureCLI@2
            displayName: "Deploy Linux VMSS"
            inputs:
              azureSubscription: $(AZURE_SERVICE_CONNECTION)
              scriptType: bash
              scriptLocation: scriptPath
              scriptPath: "$(Build.SourcesDirectory)/azure-container-networking/.pipelines/swiftv2-long-running/scripts/deploy_linuxbyon.sh"
              arguments: >
                $(rgName)
                $(Build.SourcesDirectory)
            env:
              SSH_PUBLIC_KEY_SECRET_NAME: $(SSH_PUBLIC_KEY_SECRET_NAME)
              CLUSTER_KUBECONFIG_KEYVAULT_NAME: $(CLUSTER_KUBECONFIG_KEYVAULT_NAME)
              KEY_VAULT_RESOURCE_GROUP: $(KEY_VAULT_RESOURCE_GROUP)
              KEY_VAULT_SUBSCRIPTION: $(KEY_VAULT_SUBSCRIPTION)
  
  # Run tests for each workload type specified in the parameter
  - ${{ each workload in parameters.workloadType }}:
    - template: datapath-tests-stage.yaml
      parameters:
        workloadType: ${{ workload }}
        subscriptionId: ${{ parameters.subscriptionId }}
        rgName: $(rgName)
        storageAccount1: $[ stageDependencies.AKSClusterAndNetworking.NetworkingAndStorage.outputs['CreateStorageAccounts.StorageAccount1'] ]
        storageAccount2: $[ stageDependencies.AKSClusterAndNetworking.NetworkingAndStorage.outputs['CreateStorageAccounts.StorageAccount2'] ]
        runSetupStages: ${{ parameters.runSetupStages }}
        ${{ if eq(workload, 'swiftv2-linux') }}:
          dependsOn: 
            - AKSClusterAndNetworking
        ${{ else }}:
          dependsOn: 
            - AKSClusterAndNetworking
            - DataPathTests_swiftv2_linux